### ISSUE TITLE
Flaky unit test

### ISSUE THREAD

**Issue by jimrandomh** [LessWrong2/Lesswrong2#1044]
We have a flaky unit test. When it fails, the failure looks like [this](https://circleci.com/gh/LessWrong2/Lesswrong2/1017):

```
I20180921-02:20:06.851(0)?   1) notification generation generates notifications for new private messages:
I20180921-02:20:06.852(0)?      AssertionError: expected [] to have a length of 1 but got 0
I20180921-02:20:06.852(0)?       at Assertion.assertLength (packages/practicalmeteor_chai.js:1887:10)
I20180921-02:20:06.852(0)?       at Assertion.ctx.(anonymous function) (packages/practicalmeteor_chai.js:4053:25)
I20180921-02:20:06.852(0)?       at doAsserterAsyncAndAddThen (/home/circleci/app/node_modules/chai-as-promised/lib/chai-as-promised.js:289:22)
I20180921-02:20:06.853(0)?       at Assertion.<anonymous> (/home/circleci/app/node_modules/chai-as-promised/lib/chai-as-promised.js:255:20)
I20180921-02:20:06.853(0)?       at Assertion.ctx.(anonymous function) [as lengthOf] (packages/practicalmeteor_chai.js:5102:33)
I20180921-02:20:06.853(0)?       at Promise.asyncApply (packages/local-test:lesswrong/lib/collections/notifications/tests.js:120:33)
I20180921-02:20:06.853(0)?       at /home/circleci/.meteor/packages/promise/.0.11.1.ihl06c.0g81b++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
I20180921-02:20:06.853(0)?    => awaited here:
I20180921-02:20:06.854(0)?       at Function.Promise.await (/home/circleci/.meteor/packages/promise/.0.11.1.ihl06c.0g81b++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
I20180921-02:20:06.854(0)?       at Promise.asyncApply (packages/lesswrong/testing/utils.js:117:7)
I20180921-02:20:06.854(0)?       at /home/circleci/.meteor/packages/promise/.0.11.1.ihl06c.0g81b++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
```

**Comment by jimrandomh** [comment]
The issue here is a race condition: the unit test does some things that generate a notification, then check for the notification, but the callback that actually creates the notification is asynchronous and you have to wait a little bit before it appears reliably.

This would be pretty ignorable, except that the notifications rework needs a lot more unit tests that're going to run into the same issue. So, I'm going to first make this happen reproducibly by putting a timed wait in the test, then fix it and take out the timed wait, and maybe make some notifications unit-test infrastructure in the process.
