### ISSUE TITLE
Post-page SSR broken for some Sequences posts

### ISSUE THREAD

**Issue by jimrandomh** [LessWrong2/Lesswrong2#1087]
Some Sequences posts, eg https://www.lesswrong.com/s/HXkpm9b8o964jbQ89/p/ENBzEkoyvdakz4w5d , fail during server-side rendering (but then go on to client-side render okay) for logged-out users. The server stderr then contains the following:

```
W20181014-17:19:29.722(-4)? (STDERR) Error: {"id":"app.operation_not_allowed","value":""}
W20181014-17:19:29.723(-4)? (STDERR)     at Object.Utils.performCheck (packages/vulcan:lib/lib/modules/utils.js:484:11)
W20181014-17:19:29.724(-4)? (STDERR)     at Promise.asyncApply (packages/vulcan:core/lib/modules/default_resolvers.js:130:17)
W20181014-17:19:29.724(-4)? (STDERR)     at /home/jbabcock/.meteor/packages/promise/.0.11.1.t4780s.tzczc++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
```

**Comment by jimrandomh** [comment]
It specifically affects the first and last post within a sequence, and specifically seems to be the result of `SequencesNavigationLink` in grayed-out mode.

What's happening is that `SequencesNavigationLink` uses the `withDocument` higher-order component and receives either a `documentId` or a `slug`, except that in the case where it's off the end of a sequence, it receives neither. This would be fine, since `SequencesNavigationLink` knows that it's supposed to be a grayed-out button in this case, and isn't using any of the stuff `withDocument` gives it anyways. It then makes a query without a search term, resulting in an arbitrary post. Which is, of course, in someone's drafts folder, so you don't have permission to load it. gg.
