### ISSUE TITLE
Investigate failing unit test that bypassed CircleCI

### ISSUE THREAD

**Issue by jimrandomh** [LessWrong2/Lesswrong2#1244]
The output from a run of our unit tests includes a lot of spam. Mixed in with that spam, it looks like there are some cases where the test legitimately failed (a chai assertion didn't pass), but the error went to stderr without making the test officially fail. For example:

```
W20181031-00:44:22.359(0)? (STDERR) { AssertionError: expected 0.498037 to equal 0
W20181031-00:44:22.359(0)? (STDERR)     at Assertion.assertEqual (packages/practicalmeteor_chai.js:1420:12)
W20181031-00:44:22.360(0)? (STDERR)     at Assertion.ctx.(anonymous function) (packages/practicalmeteor_chai.js:3662:25)
W20181031-00:44:22.360(0)? (STDERR)     at doAsserterAsyncAndAddThen (/home/circleci/app/lesswrong/node_modules/chai-as-promised/lib/chai-as-promised.js:289:22)
W20181031-00:44:22.360(0)? (STDERR)     at Assertion.<anonymous> (/home/circleci/app/lesswrong/node_modules/chai-as-promised/lib/chai-as-promised.js:255:20)
W20181031-00:44:22.360(0)? (STDERR)     at Assertion.ctx.(anonymous function) [as equal] (packages/practicalmeteor_chai.js:4564:33)
W20181031-00:44:22.360(0)? (STDERR)     at Promise.asyncApply (packages/local-test:lesswrong/testing/voting.tests.js:32:37)
W20181031-00:44:22.360(0)? (STDERR)     at /home/circleci/.meteor/packages/promise/.0.11.1.lt6vo5.rl7ft++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
W20181031-00:44:22.360(0)? (STDERR)   message: 'expected 0.498037 to equal 0',
W20181031-00:44:22.360(0)? (STDERR)   showDiff: true,
W20181031-00:44:22.360(0)? (STDERR)   actual: 0.498037,
W20181031-00:44:22.361(0)? (STDERR)   expected: 0 }
```

It looks like that particular unit test "passes" because the assertions are wrapped in a `forEach` which handles the `async`-ness of its contents incorrectly; but actually, it's been failing for a long time.

**Comment by jimrandomh** [comment]
Looks like that test is the only one that's silently failing (or at least, the only one with a mention of `chai`, our assertions library, in its stderr output). The main reason it went unnoticed is because we have a lot of tests whose output looks like this:

```
W20181031-00:44:29.630(0)? (STDERR) runGraphQL error: {"id":"app.operation_not_allowed","value":"check"}
W20181031-00:44:29.631(0)? (STDERR) [ { Error: {"id":"app.operation_not_allowed","value":"check"}
W20181031-00:44:29.631(0)? (STDERR)     at Object.Utils.performCheck (packages/vulcan:lib/lib/modules/utils.js:484:11)
W20181031-00:44:29.631(0)? (STDERR)     at Promise.asyncApply (packages/vulcan:core/lib/modules/default_mutations.js:55:15)
W20181031-00:44:29.631(0)? (STDERR)     at /home/circleci/.meteor/packages/promise/.0.11.1.lt6vo5.rl7ft++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
W20181031-00:44:29.631(0)? (STDERR)     message: '{"id":"app.operation_not_allowed","value":"check"}',
W20181031-00:44:29.631(0)? (STDERR)     locations: [ [Object] ],
W20181031-00:44:29.631(0)? (STDERR)     path: [ 'createComment' ] } ]
    ✓ CommentsNew should fail if post is commentLocked (169ms)
```

That is: we test an operation that isn't supposed to work, and GraphQL outputs a related error on stderr. I'm not really sure how to handle this correctly; it seems important to be able to read unit-test results and not have any stack traces appear in them except when something is actually wrong, but it's also important that GraphQL errors (including permissions errors) get logged in production. Maybe there's a way for unit tests to take temporary control over stderr?
