### ISSUE TITLE
Crash in user callbacks

### ISSUE THREAD

**Issue by jimrandomh** [LessWrong2/Lesswrong2#1651]
When you create a new user, an exception is thrown inside a callback:

```
I20190226-17:49:45.957(-8)? // error at callback [editorSerializationNew] in hook [user.create.before]
I20190226-17:49:47.382(-8)? TypeError: Cannot destructure property `currentUser` of 'undefined' or 'null'.
I20190226-17:49:47.384(-8)?     at editorSerializationNew (packages/lesswrong/server/editor/make_editable_callbacks.js:120:3)
I20190226-17:49:47.384(-8)?     at runCallback (packages/vulcan:lib/lib/modules/callbacks.js:93:33)
I20190226-17:49:47.386(-8)?     at packages/vulcan:lib/lib/modules/callbacks.js:141:16
I20190226-17:49:47.386(-8)?     at Array.reduce (<anonymous>)
I20190226-17:49:47.387(-8)?     at runCallbacks (packages/vulcan:lib/lib/modules/callbacks.js:121:22)
I20190226-17:49:47.388(-8)?     at AccountsServer.onCreateUserCallback [as _onCreateUserHook] (packages/vulcan:users/lib/server/on_create_user.js:55:10)
I20190226-17:49:47.390(-8)?     at AccountsServer.insertUserDoc (packages/accounts-base/accounts_server.js:1082:23)
I20190226-17:49:47.391(-8)?     at createUser (packages/accounts-password/password_server.js:1078:25)
I20190226-17:49:47.392(-8)?     at packages/accounts-password/password_server.js:1109:20
I20190226-17:49:47.393(-8)?     at tryLoginMethod (packages/accounts-base/accounts_server.js:1294:14)
I20190226-17:49:47.393(-8)?     at AccountsServer._loginMethod (packages/accounts-base/accounts_server.js:374:7)
I20190226-17:49:47.394(-8)?     at MethodInvocation.createUser (packages/accounts-password/password_server.js:1095:19)
I20190226-17:49:47.395(-8)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1767:12)
I20190226-17:49:47.395(-8)?     at DDP._CurrentMethodInvocation.withValue (packages/ddp-server/livedata_server.js:719:19)
I20190226-17:49:47.400(-8)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
I20190226-17:49:47.401(-8)?     at DDPServer._CurrentWriteFence.withValue (packages/ddp-server/livedata_server.js:717:46)
I20190226-17:49:47.401(-8)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1304:12)
I20190226-17:49:47.401(-8)?     at Promise (packages/ddp-server/livedata_server.js:715:46)
I20190226-17:49:47.401(-8)?     at new Promise (<anonymous>)
I20190226-17:49:47.401(-8)?     at Session.method (packages/ddp-server/livedata_server.js:689:23)
I20190226-17:49:47.402(-8)?     at packages/ddp-server/livedata_server.js:559:43
```

This exception gets ignored (because Vulcan's `runCallbacks` is sketchy that way), so the user still gets created fine.

This happens because the `vulcan:users` package tries to imitate the callbacks that `vulcan:lib`'s `createMutator` would call, but fails to match their calling convention; in particular, the `user.create.before` callback is called with no properties at all, so trying to destructure those properties into named arguments crashes.

**Comment by jimrandomh** [comment]
Reported upstream to Vulcan: https://github.com/VulcanJS/Vulcan/issues/2214
