### ISSUE TITLE
Basic instructions for local setup not working

### ISSUE THREAD

**Issue by nicholasRutherford** [LessWrong2/Lesswrong2#425]
OS: Ubuntu 16.04
Node Version: `v8.9.4`

Ran:
```
git clone https://github.com/Discordius/Lesswrong2.git
cd Lesswrong2
npm install
npm start
```
And got:
```
niko@sebastion:~/code_projects/Lesswrong2$ npm start

> Vulcan@1.8.9 prestart /home/niko/code_projects/Lesswrong2
> bash prestart_lesswrong.sh

🌋  Welcome to the LessWrong development server!
📖  We are using Vulcan, whose docs are available at: http://docs.vulcanjs.org
📖  You can find our Github repo here: https://github.com/Discordius/Telescope/tree/devel

> Vulcan@1.8.9 start /home/niko/code_projects/Lesswrong2
> meteor --settings settings.json

[[[[[ ~/code_projects/Lesswrong2 ]]]]]        

=> Started proxy.                             
packages/lesswrong/styles/main.scss.css: warn: There are some @import rules those are not taking effect as they are required to be in the beginning of the file.
=> Started MongoDB.                           
W20180224-18:07:17.452(-8)? (STDERR) /home/niko/.meteor/packages/meteor-tool/.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20180224-18:07:17.471(-8)? (STDERR) 						throw(ex);
W20180224-18:07:17.471(-8)? (STDERR) 						^
W20180224-18:07:17.471(-8)? (STDERR) 
W20180224-18:07:17.471(-8)? (STDERR) Error: Could not construct a client with those parameters
W20180224-18:07:17.471(-8)? (STDERR)     at new Client (/home/niko/code_projects/Lesswrong2/node_modules/intercom-client/dist/client.js:90:13)
W20180224-18:07:17.472(-8)? (STDERR)     at server.js (packages/lesswrong/lib/events/server.js:5:22)
W20180224-18:07:17.472(-8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:343:9)
W20180224-18:07:17.472(-8)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20180224-18:07:17.472(-8)? (STDERR)     at server.js (packages/lesswrong/server.js:1:1190)
W20180224-18:07:17.472(-8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:343:9)
W20180224-18:07:17.472(-8)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20180224-18:07:17.472(-8)? (STDERR)     at /home/niko/code_projects/Lesswrong2/.meteor/local/build/programs/server/packages/lesswrong.js:32259:15
W20180224-18:07:17.472(-8)? (STDERR)     at /home/niko/code_projects/Lesswrong2/.meteor/local/build/programs/server/packages/lesswrong.js:32264:3
W20180224-18:07:17.473(-8)? (STDERR)     at /home/niko/code_projects/Lesswrong2/.meteor/local/build/programs/server/boot.js:411:36
W20180224-18:07:17.473(-8)? (STDERR)     at Array.forEach (<anonymous>)
W20180224-18:07:17.473(-8)? (STDERR)     at /home/niko/code_projects/Lesswrong2/.meteor/local/build/programs/server/boot.js:220:19
W20180224-18:07:17.473(-8)? (STDERR)     at /home/niko/code_projects/Lesswrong2/.meteor/local/build/programs/server/boot.js:471:5
W20180224-18:07:17.473(-8)? (STDERR)     at Function.run (/home/niko/code_projects/Lesswrong2/.meteor/local/build/programs/server/profile.js:510:12)
W20180224-18:07:17.473(-8)? (STDERR)     at /home/niko/code_projects/Lesswrong2/.meteor/local/build/programs/server/boot.js:470:11
=> Exited with code: 1
W20180224-18:07:21.684(-8)? (STDERR) /home/niko/.meteor/packages/meteor-tool/.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20180224-18:07:21.684(-8)? (STDERR) 						throw(ex);
W20180224-18:07:21.684(-8)? (STDERR) 						^
W20180224-18:07:21.684(-8)? (STDERR) 
W20180224-18:07:21.685(-8)? (STDERR) Error: Could not construct a client with those parameters
W20180224-18:07:21.685(-8)? (STDERR)     at new Client (/home/niko/code_projects/Lesswrong2/node_modules/intercom-client/dist/client.js:90:13)
W20180224-18:07:21.685(-8)? (STDERR)     at server.js (packages/lesswrong/lib/events/server.js:5:22)
W20180224-18:07:21.685(-8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:343:9)
W20180224-18:07:21.685(-8)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20180224-18:07:21.685(-8)? (STDERR)     at server.js (packages/lesswrong/server.js:1:1190)
W20180224-18:07:21.685(-8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:343:9)
W20180224-18:07:21.685(-8)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20180224-18:07:21.686(-8)? (STDERR)     at /home/niko/code_projects/Lesswrong2/.meteor/local/build/programs/server/packages/lesswrong.js:32259:15
W20180224-18:07:21.686(-8)? (STDERR)     at /home/niko/code_projects/Lesswrong2/.meteor/local/build/programs/server/packages/lesswrong.js:32264:3
W20180224-18:07:21.686(-8)? (STDERR)     at /home/niko/code_projects/Lesswrong2/.meteor/local/build/programs/server/boot.js:411:36
W20180224-18:07:21.686(-8)? (STDERR)     at Array.forEach (<anonymous>)
W20180224-18:07:21.686(-8)? (STDERR)     at /home/niko/code_projects/Lesswrong2/.meteor/local/build/programs/server/boot.js:220:19
W20180224-18:07:21.686(-8)? (STDERR)     at /home/niko/code_projects/Lesswrong2/.meteor/local/build/programs/server/boot.js:471:5
W20180224-18:07:21.686(-8)? (STDERR)     at Function.run (/home/niko/code_projects/Lesswrong2/.meteor/local/build/programs/server/profile.js:510:12)
W20180224-18:07:21.686(-8)? (STDERR)     at /home/niko/code_projects/Lesswrong2/.meteor/local/build/programs/server/boot.js:470:11
=> Exited with code: 1
W20180224-18:07:26.160(-8)? (STDERR) /home/niko/.meteor/packages/meteor-tool/.1.6.1.tf1nko.5xio++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20180224-18:07:26.160(-8)? (STDERR) 						throw(ex);
W20180224-18:07:26.160(-8)? (STDERR) 						^
W20180224-18:07:26.161(-8)? (STDERR) 
W20180224-18:07:26.161(-8)? (STDERR) Error: Could not construct a client with those parameters
W20180224-18:07:26.161(-8)? (STDERR)     at new Client (/home/niko/code_projects/Lesswrong2/node_modules/intercom-client/dist/client.js:90:13)
W20180224-18:07:26.161(-8)? (STDERR)     at server.js (packages/lesswrong/lib/events/server.js:5:22)
W20180224-18:07:26.161(-8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:343:9)
W20180224-18:07:26.162(-8)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20180224-18:07:26.162(-8)? (STDERR)     at server.js (packages/lesswrong/server.js:1:1190)
W20180224-18:07:26.162(-8)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:343:9)
W20180224-18:07:26.162(-8)? (STDERR)     at require (packages/modules-runtime.js:238:16)
W20180224-18:07:26.162(-8)? (STDERR)     at /home/niko/code_projects/Lesswrong2/.meteor/local/build/programs/server/packages/lesswrong.js:32259:15
W20180224-18:07:26.163(-8)? (STDERR)     at /home/niko/code_projects/Lesswrong2/.meteor/local/build/programs/server/packages/lesswrong.js:32264:3
W20180224-18:07:26.163(-8)? (STDERR)     at /home/niko/code_projects/Lesswrong2/.meteor/local/build/programs/server/boot.js:411:36
W20180224-18:07:26.163(-8)? (STDERR)     at Array.forEach (<anonymous>)
W20180224-18:07:26.163(-8)? (STDERR)     at /home/niko/code_projects/Lesswrong2/.meteor/local/build/programs/server/boot.js:220:19
W20180224-18:07:26.163(-8)? (STDERR)     at /home/niko/code_projects/Lesswrong2/.meteor/local/build/programs/server/boot.js:471:5
W20180224-18:07:26.163(-8)? (STDERR)     at Function.run (/home/niko/code_projects/Lesswrong2/.meteor/local/build/programs/server/profile.js:510:12)
W20180224-18:07:26.164(-8)? (STDERR)     at /home/niko/code_projects/Lesswrong2/.meteor/local/build/programs/server/boot.js:470:11
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
```

**Comment by movationdesign** [comment]
Yeah I got the same, yesterday. I wanted to get the package working fast so I just removed everything that had to do with Intercom and then I got it working.  

I think the problem has something to do with the Intercom username/password, I think we need to add our own Intercom API key.

**Comment by Discordius** [comment]
Ah, yeah. Sorry. The default settings should include some dummy Intercom
info, or we should add a check that makes sure we don’t try to run Intercom
code without intercom credentials.

**Comment by movationdesign** [comment]
That would be great @Discordius 

Algolia also gives an error which aappear to be API key related — not sure though:

```
I20180226-09:10:25.160(1)? Exception in defer callback: AlgoliaSearchError: Please provide an application ID. Usage: algoliasearch(applicationID, apiKey, opts)
I20180226-09:10:25.160(1)?     at AlgoliaSearchNodeJS.AlgoliaSearchCore (/Users/davidt/Desktop/Dev/Lesswrong2/node_modules/algoliasearch/src/AlgoliaSearchCore.js:51:11)
I20180226-09:10:25.161(1)?     at AlgoliaSearchNodeJS.AlgoliaSearch (/Users/davidt/Desktop/Dev/Lesswrong2/node_modules/algoliasearch/src/AlgoliaSearch.js:11:21)
I20180226-09:10:25.161(1)?     at AlgoliaSearchNodeJS.AlgoliaSearchServer (/Users/davidt/Desktop/Dev/Lesswrong2/node_modules/algoliasearch/src/server/builds/AlgoliaSearchServer.js:17:17)
I20180226-09:10:25.161(1)?     at new AlgoliaSearchNodeJS (/Users/davidt/Desktop/Dev/Lesswrong2/node_modules/algoliasearch/src/server/builds/node.js:79:23)
I20180226-09:10:25.161(1)?     at algoliasearch (/Users/davidt/Desktop/Dev/Lesswrong2/node_modules/algoliasearch/src/server/builds/node.js:68:10)
I20180226-09:10:25.161(1)?     at algoliaDocumentExport (packages/lesswrong/lib/search/utils.js:211:16)
I20180226-09:10:25.161(1)?     at newPostAlgoliaIndex (packages/lesswrong/lib/search/callbacks.js:25:5)
```

**Comment by jimrandomh** [comment]
As of the current version, you'll get some spurious error messages related to not having API keys for Intercom/Algolia/etc, but everything other than the search bar will work without them. Feel free to message one of the core devs if you have any other problems setting up a dev environment.
