### ISSUE TITLE
Crash when editing user groups as admin

### ISSUE THREAD

**Issue by jimrandomh** [LessWrong2/Lesswrong2#799]
On my test server, going to the user profile page and adding myself to the sunshineRegiment group by clicking the "sunshineRegiment" box followed by "submit", this error appears at the top of the page:

```
Expected a field “groups.0” of type String, got “null” instead.
Expected a field “groups.1” of type String, got “null” instead.
Expected a field “groups.2” of type String, got “null” instead.
```

And this error on the server's stderr:

```
W20180810-10:40:46.665(-4)? (STDERR) // validationErrors
W20180810-10:40:46.665(-4)? (STDERR) [ { id: 'errors.expectedType',
W20180810-10:40:46.665(-4)? (STDERR)     path: 'groups.0',
W20180810-10:40:46.666(-4)? (STDERR)     properties: 
W20180810-10:40:46.666(-4)? (STDERR)      { name: 'groups.0',
W20180810-10:40:46.666(-4)? (STDERR)        value: null,
W20180810-10:40:46.666(-4)? (STDERR)        type: 'expectedType',
W20180810-10:40:46.666(-4)? (STDERR)        dataType: 'String' } },
W20180810-10:40:46.666(-4)? (STDERR)   { id: 'errors.expectedType',
W20180810-10:40:46.666(-4)? (STDERR)     path: 'groups.1',
W20180810-10:40:46.666(-4)? (STDERR)     properties: 
W20180810-10:40:46.666(-4)? (STDERR)      { name: 'groups.1',
W20180810-10:40:46.667(-4)? (STDERR)        value: null,
W20180810-10:40:46.667(-4)? (STDERR)        type: 'expectedType',
W20180810-10:40:46.667(-4)? (STDERR)        dataType: 'String' } },
W20180810-10:40:46.667(-4)? (STDERR)   { id: 'errors.expectedType',
W20180810-10:40:46.667(-4)? (STDERR)     path: 'groups.2',
W20180810-10:40:46.667(-4)? (STDERR)     properties: 
W20180810-10:40:46.667(-4)? (STDERR)      { name: 'groups.2',
W20180810-10:40:46.667(-4)? (STDERR)        value: null,
W20180810-10:40:46.667(-4)? (STDERR)        type: 'expectedType',
W20180810-10:40:46.667(-4)? (STDERR)        dataType: 'String' } } ]
W20180810-10:40:46.668(-4)? (STDERR) app.validation_error: [{"id":"errors.expectedType","path":"groups.0","properties":{"name":"groups.0","value":null,"type":"expectedType","dataType":"String"}},{"id":"errors.expectedType","path":"groups.1","properties":{"name":"groups.1","value":null,"type":"expectedType","dataType":"String"}},{"id":"errors.expectedType","path":"groups.2","properties":{"name":"groups.2","value":null,"type":"expectedType","dataType":"String"}}]
W20180810-10:40:46.668(-4)? (STDERR)     at Promise.asyncApply(packages/vulcan:lib/lib/server/mutators.js:151:13)
W20180810-10:40:46.668(-4)? (STDERR)     at /home/jbabcock/.meteor/packages/promise/.0.11.1.t4780s.tzczc++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
```

**Comment by jimrandomh** [comment]
This only seems to happen when editing groups (which are admin-only settings), not when editing any of the end-user-facing stuff.

**Comment by Discordius** [comment]
@Raemon has been working on this a bit. I don't think we figured out precisely what's up, but made some progress.

**Comment by Raemon** [comment]
I think we figured out what was wrong but not how to fix it, and meawhile I had resolved the issue at the time via brute-force-updating-the-database, but I've added this as a high priority issue which I'll work on next week.
